grader:
  working_dir: "/tmp/grader"
  grades_file: "leaderboard.json"
  github_pat: "pat_example_1234567890"
  sentry_dsn: ""

assignments:
  - name: "vector-sum"
    invite_link: "https://classroom.github.com/a/example1"
    preserve_repo_files: false

    tasks:
      - name: "test-cpu"
        skip: true
        blocking: true
        test_script_path: "./test_scripts/test_vectorsum_cpu.sh"

        slurm_backend:
          config:
            slurm_partition: "short"
            timeout_min: 60
            mem_gb: 4
            nodes: 1
            tasks_per_node: 1
            cpus_per_task: 2
            gpus_per_node: 1
      - name: "test-gpu"
        skip: false
        blocking: true
        test_script_path: "./test_scripts/test_vectorsum_gpu.sh"
        slurm_backend:
          config:
            slurm_partition: "gpu"
            timeout_min: 60
            mem_gb: 8
            nodes: 1
            tasks_per_node: 1
            cpus_per_task: 4
            gpus_per_node: 1